### ISSUE TITLE
Discuss reasoning for GAnalytics

### ISSUE THREAD

**Issue by stefanosburbaum** [CreatlV/ths-international-reception#6]

**Comment by oscsyn** [comment]
I wanted some data to see how people use the website so that we can optimize it to how people actually use it since I don't see myself as a guru that can guess the best approach the first time. I thought we wouldn't need any annoying cookie banners since we anonymize all the collected data but that's not the case, so I'll probably remove it anyway. There are some other good approaches that don't use cookies that I think we can use instead.

**Comment by oscsyn** [comment]
Removed now
