### ISSUE TITLE
General Discussion

### ISSUE THREAD

**Issue by oscsyn** [CreatlV/ths-international-reception#8]
We should move it so it's not on my personal account. Maybe move it to an organization on GitHub for all the THS projects.

**Comment by stefanosburbaum** [comment]
I'll look into it, however there will be some legal issues that we need to discuss (we didn't know about your involvment up until two days ago. @CreatlV will discuss that with you directly

**Comment by oscsyn** [comment]
I'm sad that they failed to disclose my involvement in the project. When you mention "legal issues" I get pretty upset since I've been pretty clear with my motive with the MIT license I and won't let you take my freedoms away from me. So it sounds like I won't be involed in the future of this project.

**Comment by stefanosburbaum** [comment]
We are quite stunned as well because we only learned by you writing your respective names for the different github accounts in the issues.
Please note that by legal issues we do not mean that we hold you accountable for anything.
We also understand that you want to be free in the way you work however it is in the nature of projects in collaboration with others or for someone that one has to give away some freedom. We also want our developers to be able to benefit from their work by being able to show what they have been doing but there are some implications that follow from this that we have to look after. To explain what our issue is: The problem that we are facing now as an organization is that we have two different kind of contributors to our projects and that we were forced into a specific license without being involved in that discussion. As we had similar issues already once before we are quite sensitive about that and want to make sure that everything is 100% waterproof

**Comment by CreatlV** [comment]
Let's all just find a time to discuss this together in order to solve this! 💯

**Comment by oscsyn** [comment]
It seems like a big part of this conversation is just based on us misunderstanding each other. Can you be more specific, like what is the problem with an MIT license?

**Comment by oscsyn** [comment]
I think your concerns or "issues" are unfounded and this has nothing to do with moving the repository, so I'm closing this. Contact me if you want to talk about something specific.

**Comment by stefanosburbaum** [comment]
We want to start out by saying that the situation is unfortunate and we hope we can solve it to everyone's content. Over the last days we have been looking into all the specifics about copyright and licences and here's the summary of what we are looking for: 

The MIT licence (as we understand it) compels THS International to reuse any part of the project again under the MIT licence because it does not hold the copyright on the code (a copyright holder can publish the same work under different licences). We (THS International) want to have the option, in the future, to put it under a different licence if necessary. It is quite unlikely that we ever will, but we do want to have the option. We have had similar problems before, and we do not want them again. It is the same practice that we have for everything that everyone in the team produces. Anyone following can use their work in the way they deem to be the best.

In order to solve this we would like you to give THS International the right to use your code under different licences if necessary in the future. This way, we can keep working with the MIT license set up already and no one has to give up access or use of his work to someone else. (No freedoms or credit will be taken away from anyone, but rather you give us some extra freedom).
Is this a solution that would work for you?

**Comment by oscsyn** [comment]
I really don't understand what's unfortunate. I had a fun time helping out and the only thing I asked for in return for letting you guys use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software. Is that I get credited in the source code and that I'm not to be held liable, Is that really that unreasonable? You're always just free to not use the part of the code that I made.
 
I'm happy to give you the code under another license like Apache or GPL. I just don't understand why it would ever be in my best interest to unconditionally give you the ability to hold me liable and to not give credit to my work, since you're already free to do everything else.

**Comment by stefanosburbaum** [comment]
The liability part is actually something we didn't consider before and you are right about that. We don't intend to and never will hold you liable for anything you have created that we make use of. We can put that in an agreement if it will ease your mind. Also we do not want to take away your credit in the source code, we don't mind crediting you in the repo. The only problem we see is the one sentence in the second paragraph of the MiT licence because we know from experience that this will be impossible to follow. We checked and it is possible to issue a license that removes this requirement.

**Comment by stefanosburbaum** [comment]
Closing this now as we finished our discussion with @CreatlV
